[package]
name = "ara-cli"
description = "Ara CLI program."
version = "0.1.0"
authors = ["Joe Meyer"]
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
lazy_static = "1.4.0"
ara = { path = "../ara" }